version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqlinjection_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
